# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Marshaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5 # see the latest version at https://github.com/actions/setup-go
      with:
        go-version-file: 'go.mod'

    - name: Test with coverage
      run: go test -gcflags=all=-l -count=1 -p=8 -parallel=8 -race -coverprofile=coverage.out ./... -json | tee report.json

    - name: Sonar scan
      uses: sonarsource/sonarqube-scan-action@v5 # see the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.projectKey=marshal
          -Dsonar.organization=albinzx
          -Dsonar.sources=.
          -Dsonar.exclusions=**/*_test.go
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*_test.go
          -Dsonar.scm.provider=git
          -Dsonar.go.coverage.reportPaths=coverage.out
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
